version: 2.1
orbs:
  node: circleci/node@4.7.0
  aws-cli: circleci/aws-cli@3.0.0
jobs:
  build: # Prepare the code for test and deploy
    docker:
      - image: cimg/node:17.9.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm run build
  test: # test dessert app
    docker:
      - image: cimg/node:17.9.0
    steps:
      - checkout
      - node/install
      - run: npm run test
  deploy: # deliver new version of dessert app
    docker:
      - image: cimg/node:17.9.0
    steps:
      - checkout
      - node/install
      - aws-cli/setup
      - run: |
            sudo apt update
            sudo apt install -y python3-pip python3-dev
      - run: npm install
      - run: sudo pip install awsebcli
      - run: npm run deploy:ui
      - run: npm run deploy:api
workflows:
  dessert_app:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
              branches:
                only: main # only deploy when push to main branch
